export const TEST_SPECIES = [
  {
    id: 'embercub', name: 'Embercub',
    model: {
      arch: 'quad',
      colors: { skin: '#3d3236', belly: '#6e5652', snout: '#7a605a', accent: '#2a2124', eye: '#ffb52e', glow: '#ff8a2a', inner: '#ff9a5a', horn: '#2b2326', limb: '#352b2e' },
      body: { width: 0.3, height: 0.27, length: 0.38 },
      head: { size: 0.36, snout: 0.35 },
      face: { eyes: 'round', mouth: 'smile', eyeSize: 0.3 },
      ears: { style: 'pointy', size: 0.55 },
      horns: { style: 'nub', size: 0.45, tip: 'glow', glow: 0.8 },
      tail: { style: 'flame', len: 0.45, r: 0.06 },
      pattern: { type: 'cracks', scale: 9, width: 0.06 },
    },
  },
  {
    id: 'sproutle', name: 'Sproutle',
    model: {
      arch: 'biped',
      colors: { skin: '#7cc453', belly: '#d9f0a8', accent: '#4f9a37', eye: '#5a3a1a', leaf: '#6fd04a', horn: '#9a6a3f', limb: '#6ab046', stem: '#5c9e38', flower: '#ff8fb8', inner: '#b8e886' },
      body: { r: 0.27, h: 0.42, armLen: 0.18 },
      head: { size: 0.4, faceBelly: true },
      face: { eyes: 'round', mouth: 'smile', cheeks: true, eyeSize: 0.3 },
      ears: { style: 'leaf', size: 0.55, pitch: 0.35, yaw: 1.2, tilt: 0.9, color: 'leaf' },
      horns: { style: 'wood', size: 0.3, yaw: 0.35, pitch: 0.85, minStage: 1 },
      hair: 'sprout',
      back: { style: 'moss', count: 3, size: 0.5, color: 'accent' },
    },
  },
  {
    id: 'pebblor', name: 'Pebblor',
    model: {
      arch: 'golem', rocky: true,
      colors: { skin: '#a08a74', belly: '#b89e84', accent: '#8a7560', armor: '#7d6b5a', fist: '#8f7a64', eye: '#46d0ff', glow: '#5fe0ff' },
      body: { w: 0.4, h: 0.36, d: 0.32, fist: 0.2 },
      head: { size: 0.22 },
      face: { eyes: 'round', mouth: 'smile', eyeSize: 0.34, brow: 'flat' },
      studs: { count: 5, color: '#5fe0ff', glow: 0.6, shape: 'crystal', size: 0.04 },
      back: { style: 'rocks', count: 4, size: 0.4, color: 'armor' },
    },
  },
  {
    id: 'stormeel', name: 'Stormeel',
    model: {
      arch: 'serpent',
      colors: { skin: '#2f7fd6', belly: '#ffe45a', accent: '#ffe45a', eye: '#ffffff', glow: '#fff17a' },
      body: { r: 0.12, rise: 0.7, coil: 0.32 },
      head: { size: 0.24, snout: true },
      face: { eyes: 'round', mouth: 'smile', eyeSize: 0.34 },
      back: { style: 'fins', count: 4, size: 0.9 },
      horns: { style: 'bolt', size: 0.6, pitch: 0.6, yaw: 0.5 },
      tailTip: 'bolt',
      pattern: { type: 'stripes', color: '#1f5fa8', axis: 'y', freq: 22, width: 0.25 },
      whiskers: true,
    },
  },
  {
    id: 'wispurr', name: 'Wispurr',
    model: {
      arch: 'floater',
      colors: { skin: '#9b7bff', belly: '#d8c8ff', accent: '#6b4fd8', eye: '#ffffff', glow: '#b8f2ff', inner: '#ffb8f0' },
      body: { r: 0.3, float: 0.3, shape: 'orb', arms: true, wisp: true },
      face: { eyes: 'round', mouth: 'smile', cheeks: true, eyeSize: 0.3 },
      ears: { style: 'cat', size: 0.55 },
      orbit: { count: 3, shape: 'crystal' },
      pattern: { type: 'runes', color: '#b8f2ff', scale: 4, width: 0.06 },
    },
  },
  {
    id: 'gearhawk', name: 'Gearhawk',
    model: {
      arch: 'bird',
      colors: { skin: '#9aa6b8', belly: '#e0e6f0', accent: '#ffd23f', eye: '#ff5a3a', beak: '#ffb13d', glow: '#7fe8ff' },
      body: { r: 0.3 },
      head: { size: 0.26 },
      face: { eyes: 'fierce', mouth: 'beak', brow: 'angry' },
      wings: { style: 'mech', size: 0.6, color: 'skin', accent: 'accent' },
      crest: { style: 'feather', count: 3, size: 0.8, color: 'accent' },
      tail: { style: 'feather', accent: 'accent' },
    },
  },
  {
    id: 'clankle', name: 'Clankle',
    model: {
      arch: 'insect', shell: true,
      colors: { skin: '#5a6478', shell: '#c0772c', accent: '#8a4a1a', accent2: '#3a2a20', eye: '#39e0ff', glow: '#39e0ff', limb: '#3f4556', membrane: '#cfe6ff' },
      body: { r: 0.26 },
      head: { size: 0.2 },
      horns: { style: 'rhino', size: 0.9, count: 1, pitch: 0.4, yaw: 0, color: 'shell' },
      wings: { style: 'insect', size: 0.55, minStage: 2 },
      shellStripes: true,
    },
  },
  {
    id: 'lotusnap', name: 'Lotusnap',
    model: {
      arch: 'shell', shellTop: 'lotus',
      colors: { skin: '#6fc7a0', belly: '#e8f5c8', shell: '#3f9e7a', rim: '#d8eeb0', eye: '#3a2a1a', petal: '#ffb3d9', accent: '#2f7a5c' },
      body: { r: 0.4, h: 0.28 },
      head: { size: 0.22 },
      face: { eyes: 'round', mouth: 'smile', cheeks: true },
    },
  },
  {
    id: 'ripplet', name: 'Ripplet',
    model: {
      arch: 'frog', gills: true,
      colors: { skin: '#7fd3ff', belly: '#e8f8ff', accent: '#ff8fc8', eye: '#2a1a3a', mouth: '#4a1a3a', cheek: '#ff9ac8' },
      body: { w: 0.34, h: 0.25, d: 0.3 },
      face: { eyes: 'round', mouth: 'smile', cheeks: true, eyeMounts: false, eyeYaw: 0.55 },
      tail: { style: 'fin', len: 0.4 },
      back: { style: 'fins', count: 3, size: 0.6, color: 'accent' },
    },
  },
  {
    id: 'pyroclaw', name: 'Pyroclaw',
    model: {
      arch: 'dragon',
      colors: { skin: '#d8452a', belly: '#ffcf6a', snout: '#ffb45a', accent: '#3a2522', horn: '#3a2522', eye: '#ffe45a', glow: '#ffb32a', membrane: '#ff9a3a', limb: '#c23d25' },
      horns: { style: 'back', size: 0.7, tip: 'glow', glow: 0.5 },
      ears: null,
      back: { style: 'spikes', count: 6, size: 0.5, color: 'accent' },
      tail: { style: 'flame', len: 0.9, r: 0.1, up: 0.3, spikes: 2 },
      wings: { style: 'dragon', size: 1.0, color: 'skin', membrane: 'membrane' },
    },
  },
  {
    id: 'kraken', name: 'Abyssquid',
    model: {
      arch: 'kraken',
      colors: { skin: '#5a3fa8', belly: '#ff9ad8', accent: '#ff9ad8', eye: '#ffe45a', glow: '#7ff0ff' },
      body: { r: 0.32, tent: 8 },
      face: { eyes: 'round', mouth: 'smile', eyeSize: 0.3 },
      pattern: { type: 'spots', color: '#8a6fe0', scale: 8, threshold: 0.55 },
      glowTent: true,
    },
  },
  {
    id: 'crab', name: 'Tidebreaker',
    model: {
      arch: 'crab',
      colors: { skin: '#e8603a', belly: '#ffd0a0', accent: '#b8402a', claw: '#ff7a4a', eye: '#1a1a2a' },
      body: { w: 0.4, h: 0.2, d: 0.3 },
      back: { style: 'spikes', count: 3, size: 0.4, color: 'accent' },
    },
  },
  {
    id: 'whale', name: 'Celestwhal',
    model: {
      arch: 'whale', bellyStripes: true,
      colors: { skin: '#3a4fa8', belly: '#dfe8ff', accent: '#8fd8ff', eye: '#ffffff', glow: '#ffe89a' },
      body: { r: 0.36, len: 0.75 },
      face: { eyes: 'round', mouth: 'smile' },
      halo: {},
      pattern: { type: 'spots', color: '#fff6b0', scale: 10, threshold: 0.72 },
    },
  },
];
